quizcracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_end, name='login'),
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout_view')
]

student/models.py
from django.db import models

# Create your models here.


# class Student(models.Model):
#     user = models.OneToOneField('user.User', on_delete=models.CASCADE, primary_key=True)
#     tests = models.ManyToManyField('teacher.Test', through='TestTaken')


class TestTaken(models.Model):
    student = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)
    test = models.ForeignKey('teacher.Test', on_delete=models.CASCADE)
    points = models.FloatField()


class StudentResponse(models.Model):
    student = models.ForeignKey('user.User', on_delete=models.CASCADE)
    answer = models.ForeignKey('teacher.Option', on_delete=models.CASCADE)

teacher/models.py
from django.db import models

# Create your models here.


class Subject(models.Model):
    subject_name = models.CharField(max_length=100)


class Test(models.Model):
    test_name = models.CharField(max_length=150)
    test_start_time = models.DateTimeField()
    # test_end_time = models.DateTimeField()
    test_total_mins = models.IntegerField()
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE, null=True)
    students = models.ManyToManyField('user.User')

    def __str__(self):
        return self.test_name


class Question(models.Model):
    question_text = models.TextField()
    subject = models.ForeignKey('teacher.Subject', on_delete=models.CASCADE)
    difficulty = models.CharField(max_length=15)
    correct_option = models.ForeignKey('Option', on_delete=models.SET_NULL, related_name='correct_ans', null=True)
    test = models.ForeignKey('Test', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.question_text[:30] + '...'


class Option(models.Model):
    option_text = models.CharField(max_length=150)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)

templates/exam_result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuizCracker - Result</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/exam_res.css' %}">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/ef0c98a01c.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="main" role="main">
        <section class="sticky main">
            <div class="result">
                <div class="col-xs-12 col-lg-11 wrapper-result">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="result-title">{{ exam_name }}</div>
                        </div>
                        <div class="col-sm-12">
                            <div class="heading-section">
                                <div class="result-wrapper">
                                    <div class="result-box">
                                        <div style="width: 50px; height:30px; color:white; padding-top:8px;"><i class="fas fa-award fa-4x"></i></div>
                                        <div class="result_tab">
                                            <div class="result-heading">Score</div>
                                            <div class="result-value">
                                                {{ test_taken.points }}/{{ test.question_set.count }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="result-box">
                                        <div style="width: 50px; height:30px; color:white; padding-top:8px; margin-right:15px;"><i class="fas fa-check fa-4x"></i></div>
                                        <div class="result_tab">
                                            <div class="result-heading">Correct Answers</div>
                                            <div class="result-value">
                                                {{ test_taken.points }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="result-box">
                                        <div style="width: 50px; height:30px; color:white; padding-top:8px;"><i class="fas fa-times fa-4x"></i></div>
                                        <div class="result_tab">
                                            <div class="result-heading">Wrong Answers</div>
                                            <div class="result-value">
                                                {{ wrong_a }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>QuizCracker</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
	<style>
		.vertical-center {
	      min-height: 100%;
	      min-height: 100vh;

	      display: flex;
	      align-items: center;
	    }
	    .jumbotron.vertical-center {
	      margin-bottom: 0;
	    }
	</style>
</head>
<body>
	<div class="jumbotron vertical-center">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<div class="row">
						<img src="{% static 'assets/images/logo_full.png' %}" alt="QuizCracker" class="img-fluid">
					</div>
					<div class="d-flex justify-content-center">
						<a role="button" href="{% url 'login' %}" class="btn btn-outline-danger btn-lg m-2"><i class="fa fa-sign-in"></i> Login</a>
						<a role="button" href="{% url 'register' %}" class="btn btn-outline-info btn-lg m-2"><i class="fas fa-user-plus"></i> Register</a>
					</div>
				</div>
				<div class="col-md-6">
						<div class="embed-responsive embed-responsive-16by9">
							<iframe src="https://onedrive.live.com/embed?cid=6AD0ECA4F39E147B&amp;resid=6AD0ECA4F39E147B%21485&amp;authkey=AKQ-2p4I3_K5MT4&amp;em=2&amp;wdAr=1.7777777777777777" frameborder="0"></iframe>
						</div>
				</div>
			</div>
		</div>
	</div>
{% if messages %}
    {% for message in messages %}
        <script>
            {% if message.tags == 'error' %}
                Swal.fire('Oops...','{{ message|safe }}','error');
            {% endif %}
            {% if message.tags == 'warning' %}
                Swal.fire('Warning','{{ message|safe }}','warning');
            {% endif %}
            {% if message.tags == 'info' %}
                Swal.fire('Information','{{ message|safe }}','info');
            {% endif %}
            {% if message.tags == 'success' %}
                Swal.fire('Success','{{ message|safe }}','success');
            {% endif %}
        </script>
    {% endfor %}
{% endif %}
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>QuizCracker</title>
	 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.min.css">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  <style>
    #eye_btn, #eye_btn:hover{
      color: #333;
      text-decoration: none;
    }
    .vertical-center {
      min-height: 100%;
      min-height: 100vh;

      display: flex;
      align-items: center;
    }
    .jumbotron.vertical-center {
      margin-bottom: 0;
    }
  </style>
</head>
<body>
  <div class="jumbotron vertical-center">
    <div class="container">
      <div class="d-flex justify-content-center align-items-center">
        <div class="col-md-5">
          <img src="{% static 'assets/images/logo_full.png' %}" class="img-fluid" alt="QuizCracker">
          <div class="border rounded p-3 mt-2 bg-dark text-white">
            <p class="h3">Login</p>
              <form method="post">
                  {% csrf_token %}
                  <div class="form-group" id="jgd">
                      <label for="un">Username</label>
                      <input type="text" name="username" id="un" placeholder="Enter Username" class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Password</label>
                      <div class="input-group" id="password_eye">
                        <input class="form-control" type="password" name="password" placeholder="Enter Password">
                        <div class="input-group-append">
                          <a href="" role="button" class="input-group-text" id="eye_btn"><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="d-flex justify-content-end">
{#                      <a href="#" class="text-light">Forgot Password?</a>#}
                    </div>
                    <div class="form-group mt-2">
                      <button class="btn btn-success btn-sm mt-1"><i class="fa fa-sign-in"></i> Login</button>
                      <a role="button" href="{% url 'register' %}" class="btn btn-primary btn-sm mt-1"><i class="fas fa-user-plus"></i> Register</a>
                    </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function() {
    $("#password_eye a").on('click', function(event) {
        event.preventDefault();
        if($('#password_eye input').attr("type") == "text"){
            $('#password_eye input').attr('type', 'password');
            $('#password_eye i').addClass( "fa-eye-slash" );
            $('#password_eye i').removeClass( "fa-eye" );
        }else if($('#password_eye input').attr("type") == "password"){
            $('#password_eye input').attr('type', 'text');
            $('#password_eye i').removeClass( "fa-eye-slash" );
            $('#password_eye i').addClass( "fa-eye" );
        }
    });
});
  </script>
{% if messages %}
    {% for message in messages %}
        <script>
            {% if message.tags == 'error' %}
                Swal.fire('Oops...','{{ message|safe }}','error');
            {% endif %}
            {% if message.tags == 'warning' %}
                Swal.fire('Warning','{{ message|safe }}','warning');
            {% endif %}
            {% if message.tags == 'info' %}
                Swal.fire('Information','{{ message|safe }}','info');
            {% endif %}
            {% if message.tags == 'success' %}
                Swal.fire('Success','{{ message|safe }}','success');
            {% endif %}
        </script>
    {% endfor %}
{% endif %}
</body>
</html>

templates/student-exam.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Exam</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'assets/css/offcanvas.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/exam_q.css' %}">
    <style>
    	html, body {
		  height: 100%;
		  margin: 0;
		}

		.full-height {
		  height: 91%;
		}
		.vertical-center {
	      min-height: 80%;
	      min-height: 80vh;

	      display: flex;
	      align-items: center;
	      margin-bottom: 0;
	    }
    </style>
</head>
<body class="bg-light vh-100">
	<!--======================================
		Navbar Section
	=======================================-->
	<nav class="navbar fixed-top navbar-light">
      <a class="navbar-brand" href="#">
      	<img src="/static/assets/images/logo.png" alt="QuizCracker" height="30px">QuizCracker
      </a>
    <div class="text-center pr-5">
        <strong class="h5" id="q_no">1/{{ test.question_set.all.count }}</strong>
    </div>
      <div class="text-right" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav">
            <li id="countdown" class="nav-item dropdown rounded p-1 pl-2 pr-2 bg-primary text-white" style="border-radius: 50%;">
                cc:cc:cc
            </li>
        </ul>
      </div>
    </nav>

    <!--======================================
    	Main Section 
    =======================================-->

      <div class="container-fluid text-white full-height" style="background: linear-gradient(to right, rgb(142, 45, 226), rgb(74, 0, 224));">
	      	  <div class="d-flex justify-content-center align-items-center vertical-center">
        <div class="col-md-6">
	          <div class="border bg-white text-dark p-4 shadow-lg mb-5 bg-white" style="border-radius: 20px;">
	          	<div class="text-center">
	          		<h3 class="display-5 question_text">

	          		</h3>
	          	</div>
	          	<div class="row" id="options">


	          	</div>
	          </div>
	        </div>
	      </div>
      </div>
    <div class="row p-3">
		<div class="col-6">
			<button class="btn btn-warning btn-sm mr-1 ml-1" id="prv_btn" disabled>Back</button>
			<button class="btn btn-primary btn-sm mr-1" id="next_btn" onclick="change_question(2)">Next</button>
		</div>
		<div class="col-6 text-right">
			<button class="btn btn-success btn-sm mr-1" onclick="submit_test()">Submit</button>
		</div>
	</div>
    <!-- =============================================================== -->

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'assets/js/holder.min.js' %}"></script>
    <script src="{% static 'assets/js/offcanvas.js' %}"></script>

    <script>
        let question_dict = {
            {% for question in test.question_set.all %}
                '{{ question.id }}':'{{ question.question_text }}',
            {% endfor %}
        }
        let option_dict = {
            {% for question in test.question_set.all %}
                '{{ question.id }}':[
                    {% for option in question.option_set.all %}
                    {'{{ option.id }}':'{{ option.option_text }}'},
                    {% endfor %}

                ],
            {% endfor %}
        }
        let options_ticked = {};
        $(document).ready(function () {
            const q_id = Object.keys(question_dict)[0];
            const q_text = Object.values(question_dict)[0];
            let options = Object.values(option_dict[q_id]);
            $('.question_text').html(q_text);
            $('.question_text').attr('id',`${q_id}`);
            $('#options').html('');
            console.log(options);
            for (let i=0; i<options.length; i++){
                $('#options').append('<button class="unselectMCQ" name="" onclick="tick_option('+q_id+','+Object.keys(options[i])[0]+')" ' +
                    'style="font-size:12px;padding: 10px;width: 100%;text-align: left;border: none;border-radius: 25px;margin-bottom: 10px;" ' +
                    'id="ANSWER'+Object.keys(options[i])[0]+'"> ' +
                    '<div class="row"> <div class="col-1 m-1 ">' +
                    '<h2 class="h2">'+(i+1)+'</h2></div> <div class="col-10 align-self-center"> '+ Object.values(options[i])[0] +' </div> </div> </button>');

            }
            const q_id1 = Object.keys(question_dict)[1];
            $('#next_btn').attr('onclick',`change_question(1)`);
        });
        function change_question(q_id) {
            const q_id1 = Object.keys(question_dict)[q_id];
            const q_text = Object.values(question_dict)[q_id];
            let options = option_dict[q_id1];
            $('.question_text').html(q_text);
            $('.question_text').attr('id',`${q_id1}`);
            $('#options').html('');

            for (let i=0; i<options.length; i++){
                let ticked = Object.values(options_ticked);
                let opt = parseInt(Object.keys(options[i])[0]);
                let active = ticked.includes(opt)?'ansActive':'';
                console.log(ticked)
                console.log(opt)
                console.log(active)
                console.log(Object.values(options_ticked));
                console.log(Object.keys(options[i])[0]);
                $('#options').append('<button class="unselectMCQ '+ active +'" name="" onclick="tick_option('+q_id1+','+Object.keys(options[i])[0]+')" ' +
                    'style="font-size:12px;padding: 10px;width: 100%;text-align: left;border: none;border-radius: 25px;margin-bottom: 10px;" ' +
                    'id="ANSWER'+Object.keys(options[i])[0]+'"> ' +
                    '<div class="row"> <div class="col-1 m-1 ">' +
                    '<h2 class="h2">'+(i+1)+'</h2></div> <div class="col-10 align-self-center"> '+ Object.values(options[i])[0] +' </div> </div> </button>');

            }
            $('#q_no').html(`${q_id+1}/{{ test.question_set.count }}`)
            if (q_id===0){
                $('#prv_btn').prop('disabled',true);
                $('#next_btn').prop('disabled',false);
                $('#prv_btn').attr('onclick',`change_question(${q_id-1})`);
                $('#next_btn').attr('onclick',`change_question(${q_id+1})`);
            }else if (q_id===(Object.keys(question_dict).length-1)){
                $('#next_btn').prop('disabled',true);
                $('#prv_btn').prop('disabled',false);
                $('#prv_btn').attr('onclick',`change_question(${q_id-1})`);
                $('#next_btn').attr('onclick',`change_question(${q_id+1})`);
            }else {
                $('#prv_btn').prop('disabled',false);
                $('#next_btn').prop('disabled',false);
                $('#prv_btn').attr('onclick',`change_question(${q_id-1})`);
                $('#next_btn').attr('onclick',`change_question(${q_id+1})`);
            }
        }
        function tick_option(q_id, o_id) {
            $('.unselectMCQ').each(function () {
                $(this).removeClass('ansActive');
            });

            $('#ANSWER'+o_id).addClass('ansActive');
            options_ticked[q_id] = o_id;
        }
        function submit_test() {
            let url = "{% url 'ajax_submit' %}";
            const opt_list = Object.values(options_ticked);

            if(confirm("Are you sure you want to submit?")){
                $.ajax({
                    url: url,
                    data: {
                        'option_list': opt_list,
                        'test_id': {{ test.id }}
                    },
                    success: function (data){
                        window.location.href = "{% url 'exam_result' test.id %}";
                    },
                    error: function(xhr, type, exception){
                        alert(exception)
                    }
                });
            }
        }
        function submit() {
            let url = "{% url 'ajax_submit' %}";
            const opt_list = Object.values(options_ticked);
            if(true){
                $.ajax({
                    url: url,
                    data: {
                        'option_list': opt_list,
                        'test_id': {{ test.id }}
                    },
                    success: function (data){
                        window.location.href = "{% url 'exam_result' test.id %}";
                    },
                    error: function(xhr, type, exception){
                        alert(exception)
                    }
                });
            }
        }
    let seconds;
	if(sessionStorage.getItem('seconds') == null){
        seconds = parseInt({{ test.test_total_mins }})*60;
    }else{
        seconds = sessionStorage.getItem('seconds');
    }
	function timer() {
		var hours       = Math.floor(seconds/3600);
		var minutesLeft = Math.floor((seconds) - (hours*3600));
		var minutes     = Math.floor(minutesLeft/60);
		var remainingSeconds = seconds % 60;
		if (remainingSeconds < 10) {
			remainingSeconds = "0" + remainingSeconds;
		}
		if (minutes < 10) {
		  minutes = "0" + minutes;
	  }
	  if (hours < 10) {
		hours = "0" + hours;
	  }
		document.getElementById('countdown').innerHTML = hours + ":" + minutes + ":" + remainingSeconds;
		if (seconds == 1) {
			clearInterval(countdownTimer);
			document.getElementById('countdown').innerHTML = "00:00:00";
			submit();
		} else {
			seconds--;
			sessionStorage.setItem('seconds', seconds);
		}
	}
	var countdownTimer = setInterval('timer()', 1000);
    </script>
{% if messages %}
    {% for message in messages %}
        <script>
            {% if message.tags == 'error' %}
                Swal.fire('Oops...','{{ message|safe }}','error');
            {% endif %}
            {% if message.tags == 'warning' %}
                Swal.fire('Warning','{{ message|safe }}','warning');
            {% endif %}
            {% if message.tags == 'info' %}
                Swal.fire('Information','{{ message|safe }}','info');
            {% endif %}
            {% if message.tags == 'success' %}
                Swal.fire('Success','{{ message|safe }}','success');
            {% endif %}
        </script>
    {% endfor %}
{% endif %}
</body>
</html>

templates/teacher-results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Teacher - Results</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'assets/css/offcanvas.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.min.css">
</head>
<body class="bg-light">
	<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
      	<img src="{% static 'assets/images/logo.png' %}" alt="QuizCracker" height="30px">QuizCracker
      </a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'teacher_dashboard' %}">Dashboard <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'set_subjects_tch' %}">Subjects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'set_questions_tch' %}">
              <span data-feather="help-circle"></span>
              Question List
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'set_exam_tch' %}">
              <span data-feather="edit-3"></span>
              Exams
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'view_result_tch' %}">
              <span data-feather="bar-chart"></span>
              Results
            </a>
          </li>
          
        </ul>
        <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Teacher
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'logout_view' %}">Logout</a>
                    </div>
                </li>
            </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="d-flex justify-content-between my-3 flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">
        	Results
        </h1>
        
      </div>
        {% for test in tests %}
                    <h5 class="display-5">{{ test.test_name }}</h5>
                        <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Student</th>
                                <th>Score</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for testtaken in test.testtaken_set.all %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ testtaken.student.first_name }} {{ testtaken.student.last_name }}</td>
                                    <td>{{ testtaken.points }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                        </div>
                    {% endfor %}
    </main>

    <!-- =============================================================== -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="{% static 'assets/js/holder.min.js' %}"></script>
    <script src="{% static 'assets/js/offcanvas.js' %}"></script>
{% if messages %}
    {% for message in messages %}
        <script>
            {% if message.tags == 'error' %}
                Swal.fire('Oops...','{{ message|safe }}','error');
            {% endif %}
            {% if message.tags == 'warning' %}
                Swal.fire('Warning','{{ message|safe }}','warning');
            {% endif %}
            {% if message.tags == 'info' %}
                Swal.fire('Information','{{ message|safe }}','info');
            {% endif %}
            {% if message.tags == 'success' %}
                Swal.fire('Success','{{ message|safe }}','success');
            {% endif %}
        </script>
    {% endfor %}
{% endif %}
</body>
</html>